### PR TITLE
Fix JRubyCacheBackend::canUseUnsafeCHM on Android

### PR DESCRIPTION
**Pull request by donv**
Avoid NullpointerException if t.getMessage() is null and detect "intrinsics" message in causing exception.
Both of these occur on Android.

### CODE REVIEW

**Comment by jdantonio** [comment]
Thank you!

**Comment by donv** [comment]
Hi @jdantonio !

Could you release this change or make it possible to use master from GitHub with JRuby?

What is needed for using master directly in a Gemfile with JRuby is a precompiled JAR or a build step to compile the jar after checkout (using extconf, I think).

**Comment by jdantonio** [comment]
@donv It's been almost a year since the last release so I think a new release is warranted. I'll check with the team to make sure everyone is OK with that.

**Comment by donv** [comment]
Thanks!

**Comment by thedarkone** [comment]
From me it's: :ship: :shipit:.

**Comment by jdantonio** [comment]
@donv I'm updating the project config (TravisCI, Coveralls, etc.) in #11. Once that's all working properly I'll create the next release. Probably tomorrow. Definitely this week.

**Comment by donv** [comment]
@jdantonio Thanks!  Appreciated :smile:

**Comment by jdantonio** [comment]
@donv I've released v0.3.5 with this patch. This is the first time I've pushed an update to this gem so please let me know ASAP of you have any issues!

**Comment by donv** [comment]
I ran our tests with the new version, and I got an error.  I will investigate, but it is hard to trace these errors, so it will take some time.

The visible error is

```
load error: fileutils -- java.lang.ArrayIndexOutOfBoundsException: length=256; index=1115438672
```

but that is likely a result of another error.  I'll keep you informed.

**Pull request merged**
